#!/bin/bash
chmod +x stock.py
sudo apt install sqlite3
pip install db-sqlite3 
pip install datetime
pip install tabulate
var_path=$PWD
(crontab -l; echo "* 16 * * 1-5 /bin/bash -c $var_path/runner";) | crontab -

